### ISSUE TITLE
phrase "Attending" in events module

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1265]
in events module i can not translate the phrase "Attending".

**Comment by neil96** [comment]
Fixed on 4.3.1

**Comment by lordofnos** [comment]
not fixed for me in 4.3.1. i have done the update stepps to find missing phrases...
