### ISSUE TITLE
Ad Module V4

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#158]
UserA created 3 ads.
Here is the 2, both are in pending payment but both are having impressions and both active=N/A
The "Second Test" ad says completed with out seeing it on the user's actual browsing.
The "My first test" ad is showing up on the pages. I have 1 more ad created by other user with the same issue.
![adusera](https://cloud.githubusercontent.com/assets/13417524/8794483/d4293bc4-2f8c-11e5-8c05-649949b21441.png)

Here is the 3rd one for the same user, it has 2 clicks but in AdminCP clicks = N/A "no clicks at all".
![aduseraactive](https://cloud.githubusercontent.com/assets/13417524/8794491/e77a5b04-2f8c-11e5-9e02-ca6d7a670372.png)

So in all there 3 ads showing up at the same time in my site 2 for this user and 1 for the other. But see my setting. Even if I change it to 2, all 3 are still showing up.
![adsetting](https://cloud.githubusercontent.com/assets/13417524/8794647/1b398f04-2f8e-11e5-99ae-3c7e29ff730f.png)

![adadmin](https://cloud.githubusercontent.com/assets/13417524/8794686/83e7b922-2f8e-11e5-976d-bf794df87493.png)

**Comment by Data66PF** [comment]
Do you have ajax refresh ads enabled? If so try disabling it as it had a bug in 3.8 that I don't think was fixed yet.

**Comment by Verdz** [comment]
YES is enabled but even after disabling it still the same on all of my browser.

**Comment by Data66PF** [comment]
Did you clear cache in admincp and in browsers after making the change?

**Comment by Verdz** [comment]
YES I did a common practice now.

**Comment by Verdz** [comment]
Update in V4.0.3
Now it is showing 1/3 ad with this settings. 2 images below.
![aduseraajax](https://cloud.githubusercontent.com/assets/13417524/8876264/454d5d2a-3227-11e5-8345-986c63253a26.png)

![adsetting1](https://cloud.githubusercontent.com/assets/13417524/8876271/5001a028-3227-11e5-889b-00c479f12141.png)

But on the second image it seems that only value 1 and 0 are working.
Let say I want to show 2 or 3 ads, this will not show 2 or 3 add instead it will show all adds (works like value = 0) in above image.

If set to 1, it is working but it is showing the same ad again and again. there is rotation features.

**Comment by Verdz** [comment]
I mean there is NO Ad rotation features.

**Comment by Data66PF** [comment]
I can't reproduce any issue displaying the ads. I don't have a location set for these as that will break it. I have ajax ads disabled. I have it set for 3 to display. These are front end, user created ads. Dates and times are fine. Using win 8.1 pro with firefox browser, admin is set to see ads. When I go to different pages of the site, it changes which ads display so they are rotating for me.

**Comment by RaymondBenc** [comment]
Those specific settings/features have been removed from v4 and shouldn't have been in the AdminCP, they have now been removed for our upcoming release 4.0.5.
