### ISSUE TITLE
Picture upload is not behaving correct in Android OS

### ISSUE THREAD

**Issue by shakti7188** [moxi9/phpfox#326]
when i try to upload picture on my android Os Mobile it doesnt show gallery as an option to choose from.  I tried it on my friend's phone but the problem was same.

when i try to upload picture at facebook.com it shows "gallery" as an option to choose from.
- snapshot of phpfox pic upload options 
http://www.awesomescreenshot.com/image/475962/33e8471b82bbefe7c434fc012067f57c

-snapshot of facebook.com pic upload options (This is how it should work)
http://www.awesomescreenshot.com/image/475969/899c86547d3b28cb61d6726a2b8639c4

**Comment by SalmanKhan86** [comment]
confirmed!i have also same problem

**Comment by SalmanKhan86** [comment]
"gallery" is not showing as option at PF Community when try to upload pic.Android OS

![screenshot_2015-10-08-18-25-49](https://cloud.githubusercontent.com/assets/13433124/10366787/5c3033a6-6dea-11e5-9e7a-23f12e9ddf2b.png)

**Comment by Jinkers** [comment]
This issue is still present and able to confirm. 

However, by clicking on the documents menu, the gallery is accessible from there.

**Comment by Data66PF** [comment]
Is this still an issue in 4.1.2? Note that the demo is not yet 4.1.2 but should be upgraded soon.

**Comment by SalmanKhan86** [comment]
yes still present in 4.1.2

**Comment by neil96** [comment]
Fixed on 4.2.0

**Comment by SalmanKhan86** [comment]
when 4.2.0 is going to be released. Now current is v 4.1.2

**Comment by shakti7188** [comment]
hi, even on 4.3.1  this problem is not solved.
i tested it on v4.phpfox.com and not found the gallery option to choose images on andriod OS in PHOTOS section.
Photo upload on status post works fine.
here is the snapshot 👎 
![phtoupload-error](https://cloud.githubusercontent.com/assets/8586180/14415323/563d2f4a-ffbb-11e5-993f-2b87194e8caa.jpg)

**Comment by shakti7188** [comment]
hey, you have not open this issue till yet,  are you not taking this issue as serious problem ?
Well, i think its a serious problem for my website, if you can not solve it or dont have any interest to solve then please let me know so that i can ask my developer to correct it by modifying core for me. 

or should i write a new issue for it ?

THanks

**Comment by Data66PF** [comment]
We don't reopen issues. I see you submitted a new one though.
