### ISSUE TITLE
PF Community Feed Error

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#522]
Posting this bug per request from @RaymondBenc 

There is a random error seen in the feed. 

![feed error](https://cloud.githubusercontent.com/assets/6908282/10016231/638cbc54-60f3-11e5-9835-e27d3acb3034.png)

**Comment by RaymondBenc** [comment]
I believe this issue has been resolved in the local dev build.

**Comment by Data66PF** [comment]
This issue still persists in the live community today. V4.0.8

**Comment by AnthonyKing** [comment]
so that means the solution is on its way. 4.0.9

**Comment by Data66PF** [comment]
I still see this in 4.0.9 at the live community.
