### ISSUE TITLE
Hashtag Issue in Unicode Character 

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#631]
when i use INDIA Hindi language in my #tag then not working correctly.in url its breaks into different words. some Unicode character issue is there.testing on PF Community

![hashtag hindi character issue](https://cloud.githubusercontent.com/assets/13433124/10535127/a808b9b0-73fd-11e5-8948-0a400f4d2933.png)

**Comment by Data66PF** [comment]
http://community.phpfox.com/hashtag/%E0%A4%B8%E0%A5%81%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%AD%E0%A4%BE%E0%A4%A4/

well I confirmed at the community but have no idea why the link I'm trying to copy posts here like that.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-78 *

**Comment by Criotin** [comment]
Not fixed.

![hashtag](https://cloud.githubusercontent.com/assets/15389101/18485211/8fcb3906-79f4-11e6-9074-8ea770174993.png)

**Comment by neil96** [comment]
@Criotin Please open a new issue if you can reproduce this issue again.
