### ISSUE TITLE
Responsiveness Issues on Main Login Screen, Feed, Site... (community.phpfox.com)

### ISSUE THREAD

**Issue by brightboss** [moxi9/phpfox#66]
There is Empty space between main background photo and responsive main menu tab with the color of the main theme.   Shouldn't it be the signup box, menu and background? Please review attached screen shot.
![phpfox-empty-space-login-01](https://cloud.githubusercontent.com/assets/13282692/8636906/d440a266-282d-11e5-9e88-8e2cd895fb67.jpg)

When browsing main feed and user has posted a big photo, responsiveness breaks...
![phpfox-responsive-issue-02](https://cloud.githubusercontent.com/assets/13282692/8636925/c7ad3c70-282e-11e5-8abe-28f0f4866330.jpg)
![phpfox-responsive-issue-03](https://cloud.githubusercontent.com/assets/13282692/8636926/d05a5efc-282e-11e5-8aaa-64ad97d86929.jpg)

**Comment by RaymondBenc** [comment]
The first issue has been fixed in #59 

Will take a look into the other issues mentioned in the report.

**Comment by brightboss** [comment]
The 1st issue is still there in #59 Please view screen shots from my iPhone. The grey area between background photo is still there.

![image64b91](https://cloud.githubusercontent.com/assets/13282692/8641807/71be4254-28cf-11e5-8959-f49a1eecc0db.jpg)
![image01066](https://cloud.githubusercontent.com/assets/13282692/8641812/83012f40-28cf-11e5-8194-8cf373cca581.jpg)
![image80650](https://cloud.githubusercontent.com/assets/13282692/8641815/8ed6125e-28cf-11e5-8693-b76273322551.jpg)
![imageef130](https://cloud.githubusercontent.com/assets/13282692/8641822/a16a53e4-28cf-11e5-8b01-1eca0d024565.jpg)
