### ISSUE TITLE
Bootsrap theme . feed issue

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#780]
whenever I post something,  immediately after posting I am getting this alert as shown below.
using chrome with lastest release.
![image](https://cloud.githubusercontent.com/assets/406030/11608679/92933a70-9b70-11e5-88aa-da80c2f25cc7.png)

**Comment by robert9592** [comment]
Fixed in v4.1.2

**Comment by Data66PF** [comment]
issue is still seen in our staging site. please test there. It shows continually that I have new updates and when I click, it says I have no new updates.

**Comment by Data66PF** [comment]
Issue appears continually only up to a point and then it disappears. This needs more testing to see why it is behaving like this. I had visited a profile and then it showed 785 new feeds. I clicked but it said no new feeds. Perhaps it is a random issue now.
