### ISSUE TITLE
Friend request issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#784]
I have still thish issue. https://github.com/moxi9/phpfox/issues/406
I see still ""Pending Friend Request"" on user profile
I cleared cache and updated counters.

**Comment by Data66PF** [comment]
Cannot reproduce for new pending requests. Please ensure you closed out the old ones (removed them).

**Comment by Ylmzef** [comment]
It's about old requests.

**Comment by Data66PF** [comment]
You need to clear out the old ones manually.

**Comment by Ylmzef** [comment]
There no information about that.

**Comment by Data66PF** [comment]
".... click the x in the lower right corner of the profile pic when viewing the pending and click to remove it" is how to remove the old ones.

**Comment by Ylmzef** [comment]
I see this "There are no pending friends requests." on /friend/pending/ page.
But on user profile i see "Pending Friend Request" message on user profile page.

**Comment by neil96** [comment]
On V3, we have this setting: "friend.hide_denied_requests_from_pending_list". If enabled, friend requests that were denied will be hidden from the Pending Friend Requests list. I think I will bring back this setting for admin can choose.

**Comment by Ylmzef** [comment]
What is solution for currenlty?

**Comment by Data66PF** [comment]
You would want to wait for us to release the fix.

**Comment by neil96** [comment]
We bring back this setting: "Hide denied requests from pending list" on 4.1.2
To view this setting, go to: admincp->settings->modules->friends

**Comment by Vivian-phpFox** [comment]
Fixed in V4.1.2

**Comment by Ylmzef** [comment]
I enabled it but the friend requests still showing on profile as "Pending Friend Request
"

**Comment by Data66PF** [comment]
Please open a new bug report for the issue as closed issues need a new bug report and I'll confirm the  issue for the new report.
